CREATE DATABASE IF NOT EXISTS bd_bodegas;
CREATE DATABASE IF NOT EXISTS bd_clientes;
CREATE DATABASE IF NOT EXISTS bd_login;
CREATE DATABASE IF NOT EXISTS bd_productos;
CREATE DATABASE IF NOT EXISTS bd_proveedores;
CREATE DATABASE IF NOT EXISTS bd_sucursales;
CREATE DATABASE IF NOT EXISTS bd_vendedores;
CREATE DATABASE IF NOT EXISTS bd_ventas;