spring.application.name=api-gateway

# Puerto del Gateway
server.port=8080

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Ruta para el microservicio de LOGIN
spring.cloud.gateway.server.webflux.routes[0].id=login-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://login-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/login/**

# Ruta para el microservicio de VENDEDORES
spring.cloud.gateway.server.webflux.routes[1].id=vendedores-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://vendedores-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/vendedores/**

# Ruta para el microservicio de CLIENTES
spring.cloud.gateway.server.webflux.routes[2].id=clientes-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://clientes-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/clientes/**

# Ruta para el microservicio de SUCURSALES
spring.cloud.gateway.server.webflux.routes[3].id=sucursales-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://sucursales-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/sucursales/**

# Ruta para el microservicio de BODEGAS
spring.cloud.gateway.server.webflux.routes[4].id=bodegas-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://bodegas-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/bodegas/**

# Ruta para el microservicio de PRODUCTOS
spring.cloud.gateway.server.webflux.routes[5].id=productos-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://productos-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/productos/**

# Ruta para el microservicio de VENTAS
spring.cloud.gateway.server.webflux.routes[6].id=ventas-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://ventas-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/ventas/**,/api/v1/detalles-venta/**

# Ruta para el microservicio de PROVEEDORES
spring.cloud.gateway.server.webflux.routes[7].id=proveedores-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://proveedores-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/proveedores/**


